### ISSUE TITLE
音频文件没有语音内容，却还是是别出了结果

### ISSUE THREAD

**Issue by Thunderltx** [yeyupiaoling/Whisper-Finetune#10]
录了一段没说话的内容，用提供的微调模型识别结果为【谢谢观看】【字幕由 Amara.org 社区提供】等结果，看了看描述，貌似是训练数据集导致的，这种问题有办法避免么

**Comment by yeyupiaoling** [comment]
这个通过训练空语音应该能够缓解。但目前还不支持这种训练，后面应该会增加

**Comment by yeyupiaoling** [comment]
最新代码已经支持训练空文本。

**Comment by Thunderltx** [comment]
> 最新代码已经支持训练空文本。

ok,我去看看
