### ISSUE TITLE
Android端的低版本能用吗？

### ISSUE THREAD

**Issue by xclidongbo** [yeyupiaoling/Whisper-Finetune#13]
android kotlin版本  1.3.41
gradle 6.5
gradle-plugin 3.6.4

**Comment by yeyupiaoling** [comment]
应该不行，我用的是最新的android studio，变动很大。

**Comment by xclidongbo** [comment]
我也看了官方的react native demo。Android端的gradle到7.2.1，kotlin的版本是1.7了。

**Comment by xclidongbo** [comment]
我对Android理解的不深刻，所以才想问题，低版本集成的可能性。
如果实在不行，我看看能否升级。 毕竟老项目，要动的东西太多。

**Comment by yeyupiaoling** [comment]
这个我也不太清楚。 试过才知道。
