### ISSUE TITLE
accelerate方式训练是否支持deepspeed？

### ISSUE THREAD

**Issue by Johnson-NLP** [yeyupiaoling/Whisper-Finetune#14]
很好的项目，Star了

请教下使用accelerate方式多卡训练时，是否支持deepspeed的ZERO stage优化显存占用？我这边单卡显存太小了，无法开更多的batch size
谢谢

**Comment by Johnson-NLP** [comment]
我这边尝试了一下在accelerate config时配置deepspeed，但是没有效果，无论用stage多少显存都无变化

**Comment by yeyupiaoling** [comment]
这个不支持哦。

**Comment by yeyupiaoling** [comment]
官方那个虽然支持，但是如果要使用的话，应该是要特殊的处理的，但是我没有做。

**Comment by yeyupiaoling** [comment]
如果你显存不够的话，可以开启量化8位。

**Comment by Johnson-NLP** [comment]
哦哦好的我再研究下，谢谢
