### ISSUE TITLE
关于whisper微调

### ISSUE THREAD

**Issue by ouyang982020** [yeyupiaoling/Whisper-Finetune#15]
您好，最近开始关注语音转文字这一块，我使用原始的large-v2模型进行语音转文字，基本不会出现语气词和结巴导致出现的重复词，但是按照您这个微调之后，出现了这类转文字情况，但是我看语料里面也没有教模型去识别语气词，是什么原因呢？

**Comment by yeyupiaoling** [comment]
你用你的数据微调的吗？数据量怎么样？

**Comment by ouyang982020** [comment]
使用的是你给的数据微调的

**Comment by ouyang982020** [comment]
具体来讲，就是使用largv2模型加上您这边语料进行微调，然后我这边拿了一个本地音频进行测试，发现识别效果可能还没原始的large-v2好，甚至模型还学会了将那些讲话结巴的词汇识别出来，我觉得这样很不友好，比如有人讲话”就就就~“，它会全部识别，原始的模型是不会这么识别的，会过滤掉这种结巴导致的重复词

**Comment by yeyupiaoling** [comment]
我的语料是指哪些，aishell吗？你有没有试过直接下载我训练好的模型，也会出现这种情况吗？

**Comment by ouyang982020** [comment]
对，尝试了直接下载好的模型，不会出现，但是训练的步骤确实是按照readme执行，现在我进入了群聊，后续通过群聊和您沟通？

**Comment by yeyupiaoling** [comment]
你试一下用最新代码跑去看会不会出现同样的情况。

**Comment by ouyang982020** [comment]
请问一下wenetspeech数据集音频在哪里下载呢？

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/PPASR/blob/develop/docs/wenetspeech.md
