### ISSUE TITLE
Error: libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by xiaobuguilaile** [yeyupiaoling/Whisper-Finetune#16]
我在CUDA version：12.0的服务器上，调用 whisper-large-v2-finetune-ct2模型，通过infer_ct2.py进行测试报了如下错误：

"Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
Aborted"

有人遇到过类似问题吗？原因是什么？具体怎么解决的？

**Comment by yeyupiaoling** [comment]
应该是环境没配好，你用conda安装试试看，或者不用这么高版本，用cuda11

**Comment by zheng1237** [comment]
> 
环境没配好，没有安装cudnn，此外，应该用cuda11

**Comment by jappre** [comment]
同样的问题，我是cuda11.7
