### ISSUE TITLE
請問您微調的模型有百度網盤以外的備份嗎?

### ISSUE THREAD

**Issue by aszk1415** [yeyupiaoling/Whisper-Finetune#19]
如題，外面很難使用百度網盤進行下載，請問有其他空間提供下載嗎?  謝謝

**Comment by yeyupiaoling** [comment]
没有哦，你是无法下载吗？还是网速慢？

**Comment by aszk1415** [comment]
台灣這邊是連百度帳戶都不能申辦，因為要綁定大陸手機號，我用motrix加上百度網盤aria2的方式則是慢到幾乎下不下來

**Comment by yeyupiaoling** [comment]
> 中國台灣這邊是連百度帳戶都不能申辦，因為要綁定大陸手機號，我用motrix加上百度網盤aria2的方式則是慢到幾乎下不下來

@aszk1415 阿里云盘你能用吗？只有这两种方法了。

**Comment by yeyupiaoling** [comment]
话说你要下载哪个模型？或者可以下载官方的，然后转换。又或者直接微调。

**Comment by yeyupiaoling** [comment]
@aszk1415 解决了吗？解决了我就关闭这个issue
