### ISSUE TITLE
whisper CTranslate2加速推理和GGML加速推理 测试过可以用吗？速度能快多少

### ISSUE THREAD

**Issue by wchuan163** [yeyupiaoling/Whisper-Finetune#20]

**Comment by ILG2021** [comment]
faster_whisper就是使用ctranslate2推理。原作者给的参数是4倍加速。另外会减少显存的消耗。使用ctranslate2普通显卡也可以使用large-v2。

**Comment by lemonriver** [comment]
https://github.com/ggerganov/whisper.cpp/discussions/589

**Comment by wchuan163** [comment]
可以做到实时语音识别吗？实时字幕， 说完一句传过去就返回文本

**Comment by yeyupiaoling** [comment]
> 可以做到实时语音识别吗？实时字幕， 说完一句传过去就返回文本

你可以看测试表格里面的实时率。
