### ISSUE TITLE
LoRA参数

### ISSUE THREAD

**Issue by biofoolgreen** [yeyupiaoling/Whisper-Finetune#24]
使用finetune.py里的[LoRA参数](https://github.com/yeyupiaoling/Whisper-Finetune/blob/457f73e40cb6040de9d14a3886e7fcbe35960bce/finetune.py#L104)跑出来的收敛曲线跟AdaLoRA差异比较大，这是符合预期的吗？有能跟AdaLoRA收敛差不多的LoRA参数么？
![图片](https://github.com/yeyupiaoling/Whisper-Finetune/assets/8380956/74f44699-d7ef-424a-9cfe-8b7a01a8d545)

**Comment by yeyupiaoling** [comment]
符合预期的，adarola效果好一点。
你可以试试设置更大的lora参数

**Comment by biofoolgreen** [comment]
> 你可以试试设置更大的lora参数

是指把`r`设置得更大一些吗？这样训练参数更多，所以拟合能力更强？

**Comment by yeyupiaoling** [comment]
嗯，训练的参数更大，训练就更慢。

**Comment by biofoolgreen** [comment]
好的，谢谢~
