### ISSUE TITLE
微调之后的模型中还有adalora的参数吗

### ISSUE THREAD

**Issue by snsun** [yeyupiaoling/Whisper-Finetune#25]
你好，
请问微调之后，Adalora或者lora的参数，比如lora_A, lora_B，百度网盘上有保存的吗？还是都融合进了finetuning的model里面了？

**Comment by yeyupiaoling** [comment]
合并后的

**Comment by snsun** [comment]
不知道方便提供一个只有lora的参数词典吗，A,B,E，我自己微调的效果都比较差，而且encoder的前几层的lora_E的rank都是0

**Comment by yeyupiaoling** [comment]
我都是用默认的参数，没有用其他的参数。
