### ISSUE TITLE
ada lora 训练问题

### ISSUE THREAD

**Issue by tongjinle123** [yeyupiaoling/Whisper-Finetune#26]
hello，
我发现 官方的ada lora 训练是需要在zero_grad 之前手动执行model.update_and_allocate(global_step)，
参考：
https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_adalora_whisper_large_training.py#L670-L688
但是这个repo 中没有对trainer 进行修改，且 transformers 的trainer 中没有调用这个函数的地方，想跟你确认下~

**Comment by yeyupiaoling** [comment]
@tongjinle123 好像不用这个也没有问题，还是能够正常微调的。
