### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker.

### ISSUE THREAD

**Issue by donstang** [yeyupiaoling/Whisper-Finetune#3]
python finetune.py meet error.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/15995403/235102989-86490224-cbdd-4caa-9f28-47abee277d0e.png">

**Comment by yeyupiaoling** [comment]
@donstang 看样子好像数据读取出了问题。检查看一下数据列表有没有数据，然后音频文件有没有问题？

**Comment by donstang** [comment]
> @donstang 看样子好像数据读取出了问题。检查看一下数据列表有没有数据，然后音频文件有没有问题？

<img width="756" alt="image" src="https://user-images.githubusercontent.com/15995403/236114594-66c524ee-1f2d-4710-9e6e-e5c2cb5b0ef0.png">

load_dataset  validation key error write as dev

**Comment by donstang** [comment]
> @donstang 看样子好像数据读取出了问题。检查看一下数据列表有没有数据，然后音频文件有没有问题？

@yeyupiaoling 数据是正常存在的，可以做save_to_disk。但是训练的时候还是会出现问题

**Comment by donstang** [comment]
> @donstang 看样子好像数据读取出了问题。检查看一下数据列表有没有数据，然后音频文件有没有问题？

该问题已解决，重新安装了环境就可以了。感觉是python库的干扰导致上述with_transform执行不成功，最终导致数据读取的段错误。
