### ISSUE TITLE
正常数据和空数据一起训练的格式

### ISSUE THREAD

**Issue by xyx361100238** [yeyupiaoling/Whisper-Finetune#39]
你好，如果我使用正常标注（没有时间戳）和空数据一起训练，下面的格式是否正确：
{"audio": {"path": "dataset/0.wav"},"sentence": "近几年，不但我用书给女儿压岁，也劝说亲朋不要给女儿压岁钱，而改送压岁书。","language": "Chinese"} -- 正常标注
{"audio": {"path": "dataset/1.wav"},"sentence": ""}  -- 空音频或者背景音

多谢！

**Comment by yeyupiaoling** [comment]
嗯嗯，看着是正常的

**Comment by xyx361100238** [comment]
好的   多谢！试一下先

**Comment by ouyang982020** [comment]
如果带有时间戳呢，应该是什么格式

**Comment by yeyupiaoling** [comment]
看文档，有例子

**Comment by xyx361100238** [comment]
@yeyupiaoling 可以帮忙解答下，如果我要改成全量跟新，要怎么处理代码吗？

**Comment by yeyupiaoling** [comment]
@xyx361100238 应该吧lora部分去掉就可以

**Comment by ouyang982020** [comment]
> 看文档，有例子

![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/75766732/c613c8e7-b494-4001-a027-4c015f445217)
我看示例是这样的，那我这边是这么写吗
![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/75766732/b7685612-8aa9-413a-9146-e987174dfe52)

**Comment by xyx361100238** [comment]
看样子是可以的   因为我的是没有timestamp的

**Comment by yeyupiaoling** [comment]
> > 看文档，有例子
> 
> ![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/75766732/c613c8e7-b494-4001-a027-4c015f445217)
> 我看示例是这样的，那我这边是这么写吗
> ![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/75766732/b7685612-8aa9-413a-9146-e987174dfe52)

好像群里回复你了，空白的语音，sentences 为［］
