### ISSUE TITLE
2卡训练速度比单卡训练快很多

### ISSUE THREAD

**Issue by pcqiao0** [yeyupiaoling/Whisper-Finetune#40]
你好，请问为什么两卡训练的速度比单卡训练速度的2倍还要多呢？

**Comment by xyx361100238** [comment]
有没有出现添加eval过程会导致系统一直上升？（我把eval取消掉内存就比较稳定）我训练base模型已经从117G的内存上升到了227了    这个transforms的bug还是咱们的脚本需要做什么设置

**Comment by yeyupiaoling** [comment]
@xyx361100238 可能是这一步收集结果导致的，可能是你的测试数据太大了。
https://github.com/yeyupiaoling/Whisper-Finetune/blob/db8dad541434839de151f4c5d0808753852d3a0c/evaluation.py#L90

**Comment by xyx361100238** [comment]
训练过程的eval跟这个脚本的内容有关联吗？发现在训练过程内存一直在上升（数据量是挺大的，训练数据有5W+小时）

**Comment by yeyupiaoling** [comment]
训练的时候没有这步

**Comment by xyx361100238** [comment]
训练过程中，内存一直在上升，这可能是transformer的一个问题，我也给他们提了issue

**Comment by xyx361100238** [comment]
我测试了huggingface的训练代码，发现系统内存并没有上升，是不是咱们对数据的处理方式跟他不一样导致的？可以帮忙分析下吗？

**Comment by yeyupiaoling** [comment]
不太清楚你的环境，我的训练2000万条数据，2张显卡，才使用20多G内存

**Comment by xyx361100238** [comment]
可能你用的base模型，我用的large模型，80G的显存batch_size只能设置到2；4000万+条的数据系统内存直接加载到600G，然后训练过程系统内存（不是显存）一直在上升  跑两天就内存就爆了

**Comment by yeyupiaoling** [comment]
你看我的测试表，里面所有模型我都用过

**Comment by yeyupiaoling** [comment]
我说的就是内存，显存我的只有11g

**Comment by xyx361100238** [comment]
抱歉，我用原始工程测试了下，加载的数据量4700万，显卡内存≤11G  内存81G   之前对工程有些修改，出了问题

**Comment by xyx361100238** [comment]
如果我希望做到参数全量更新，是不是把LoRA那部分注释掉就可以了？ 之前台湾的一位教授讲到LoRA更新可能对语音识别的效果提升有限，我的测试发现LoRA更新确实到后面有天花板比较低

**Comment by yeyupiaoling** [comment]
你有这么大的数据集，估计全量训练效果会更佳
