### ISSUE TITLE
config.json文件与huggingface上的config.json不一样

### ISSUE THREAD

**Issue by hahazei** [yeyupiaoling/Whisper-Finetune#45]
![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/19165506/d127f430-943e-4642-80d0-d0afc8a13711)
左边是huggingface的config.json文件，右边是群主百度网盘里的config.json。想问下群主，为什么差异？有什么特别原因吗？

**Comment by yeyupiaoling** [comment]
一样的。可能那边是有更新吧
