### ISSUE TITLE
資料格式的 language 設定

### ISSUE THREAD

**Issue by ken19980727** [yeyupiaoling/Whisper-Finetune#46]
想請問各位大大
`"language": "Chinese"`
設定 `language` 對於訓練跟編碼解碼有影響嗎
謝謝!

**Comment by GabrielHaoHao** [comment]
没有影响

**Comment by GabrielHaoHao** [comment]
> 想請問各位大大 `"language": "Chinese"` 設定 `language` 對於訓練跟編碼解碼有影響嗎 謝謝!

没有影响，设为None就行
