### ISSUE TITLE
123

### ISSUE THREAD

**Issue by 20246688** [yeyupiaoling/Whisper-Finetune#49]
tensorflow.python.framework.errors_impl.FailedPreconditionError: output/基础模型 is not a directory

**Comment by yeyupiaoling** [comment]
你这个问题提得不规范

**Comment by 20246688** [comment]
佬，看2群




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月16日(星期二) 下午4:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyupiaoling/Whisper-Finetune] 123 (Issue #49)





 
关闭的#49已完成。
 
—
直接回复这封邮件，在GitHub上查看，或者取消订阅.
你收到这封邮件是因为你写了这个帖子。Message ID: ***@***.***&gt;
