### ISSUE TITLE
使用 ct2 轉換後掉辨識率

### ISSUE THREAD

**Issue by ken19980727** [yeyupiaoling/Whisper-Finetune#52]
各位大老好

我用 ct2 轉換後 RTF 是有變快
但是WER上升明顯
請問各位有遇到這種情況嗎

我是用 whisper-large-v2 做 benchmark
common voice 的 WER 上升了 3%
指令我都是用版主提供的指令
不過我沒有加 quantization 這個 function
想問有人跟我遇到一樣的問題嗎

**Comment by ken19980727** [comment]
package version:
transformers==4.36.2
peft==0.7.1
fast-whisper==0.10.0

**Comment by yeyupiaoling** [comment]
ct2会有损失吗？我也没有测试过。ct2官方也没有说明有损失。
