### ISSUE TITLE
用BELLE-2/Belle-whisper-large-v2-zh识别中文音频，效果还不如Systran/faster-whisper-large-v2？

### ISSUE THREAD

**Issue by drilistbox** [yeyupiaoling/Whisper-Finetune#54]
作者您好，我用BELLE-2/Belle-whisper-large-v2-zh跑实验 效果还不如Systran/faster-whisper-large-v2

按道理在中文数据上finetune的模型性能 应该比fasterwhisiper的好才对

![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/14495189/3db5dee2-7917-47ee-81a9-9cd0c0634bd5)

我用的测试音频文件在这里 https://drive.google.com/file/d/1UTGOlnc3c_5FDHv_hH3IyNgNjxHNKQkD/view?usp=sharing

我是这么用的
![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/14495189/74455652-82cb-45a4-8984-09980e5e7e82)
![692c67b61fa13fc8a246cefebfc31b6](https://github.com/yeyupiaoling/Whisper-Finetune/assets/14495189/de5b106a-41c7-4b9b-8d3a-231ac35a9007)

怎么才能弄出好的效果么

**Comment by yeyupiaoling** [comment]
不清楚你用的这两个模型是怎么样的。微调后提升的是你数据集的准确率。有可能是你微调的数据跟你测试的音频差异较大。

**Comment by drilistbox** [comment]
感谢
