### ISSUE TITLE
模型微调后出现乱码

### ISSUE THREAD

**Issue by hcguoO0** [yeyupiaoling/Whisper-Finetune#59]
使用Lora微调的large-v3模型，第1000step保存的模型输出还正常，但第6000step保存的模型输出就乱码了，如下图，请问这是咋回事呀
![111](https://github.com/yeyupiaoling/Whisper-Finetune/assets/140693026/8f7bd242-1f51-42dc-a7b2-de92732ba525)

**Comment by yeyupiaoling** [comment]
你的数据是多少？换其他模型是否正常？会不会是这个模型的问题？也或者说是数据太少的问题？
