### ISSUE TITLE
微調後的模型在其他語言的效果降低了??

### ISSUE THREAD

**Issue by cyc00518** [yeyupiaoling/Whisper-Finetune#6]
嗨, 大佬,
先感謝您開源了這麼棒的專案,

我成功的利用中文音頻來fine-tune模型, 

但因為在訓練代碼跟預測代碼都需指定language='zh',

造成若中英夾雜或是一串中文中有數字時,

無法像沒有fine-tune前的模組一樣表現得很好,

例如 編號89757, fine-tune後可能就會變成'編號巴舅漆舞漆'
請問有什麼辦法解決嗎? 或是可以在預測時不指定語言?

謝謝您!

**Comment by yeyupiaoling** [comment]
只有当训练的是多语种的时候才会将language设置为None。
我觉得你的问题不太可能是这个，你这种数据指定为zh微调和推理都没问题的。
当然，你也可以试试将language设置为None训练和微调试试。

**Comment by cyc00518** [comment]
好的, 我再找找看,
謝謝您!
