### ISSUE TITLE
训练出的模型如何导出npz格式

### ISSUE THREAD

**Issue by jackwenshann** [yeyupiaoling/Whisper-Finetune#68]
希望在https://github.com/usefulsensors/useful-transformers下使用微调模型，但是模型需要通过torch_state_dict_to_npz.py转换成npz格式。使用 微调后的模型在执行后报错了
   model = torch.load(pt_file)
    dims = {f'dims/{k}': v for k, v in model['dims'].items()}
    params = {f'params/{k}': v for k, v in model['model_state_dict'].items()}

**Comment by yeyupiaoling** [comment]
@jackwenshann 我项目没有提供这种转换。我也没有使用这种格式的模型，不清楚如何转换
