### ISSUE TITLE
关于微调模型的问题

### ISSUE THREAD

**Issue by ccsvd** [yeyupiaoling/Whisper-Finetune#7]
你好，有个问题想请教一下：
现在whisper不支持某个领域的专有名词，是否可以通过增加部分专有数据到现有的开源中文数据中，构成新的数据集，然后进行微调，实现对这些专有词汇的支持，如果这个方案可行的话，应该需要多少的数据量能达到较好的效果呢？并且对采集的音频数据有啥要求呢？
期待答复，不胜感激。

**Comment by yeyupiaoling** [comment]
微调你专门的数据应该是有效的，但多少条我不太清楚。你可以先尽可能收集一批微调，看一下看有没有提升。

**Comment by ccsvd** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ptdaxiake** [comment]
python infer_ct2.py --audio_path=dataset/test.wav --model_path=models/whisper-tiny-finetune-ct2

Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
已放弃（核心已转储）

**Comment by yeyupiaoling** [comment]
看报错信息，好像你的cudnn没有装。你用conda来安装，按照我的文档来安装。

**Comment by springminhcm** [comment]
你好，请教一下，关于微调模型的json档的文本，可以不使用标点符号吗？如原始内容如下：

{"audio": {"path": "dataset/audio/data_aishell/wav/test/S0764/BAC009S0764W0489.wav"}, "sentence": "不是她的戏，或是她的八卦？", "duration": 3.45}

可以改為：
{"audio": {"path": "dataset/audio/data_aishell/wav/test/S0764/BAC009S0764W0489.wav"}, "sentence": "不是她的戏或是她的八卦", "duration": 3.45}

**Comment by yeyupiaoling** [comment]
当然可以，但是微调后的模型也会丧失标点符号能力。

**Comment by springminhcm** [comment]
板主您好，我在微调模型finetune.py时，不论是用tiny、small、medium等都很容易出现以下错误，请问有什么可能原因？我是用3090gpu，参数都已设batch_size调到2，num_workers也设2....但依旧都会不定时产生错误

  File "/home/t777/anaconda3/envs/ppasr/lib/python3.8/zipfile.py", line 1535, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

**Comment by yeyupiaoling** [comment]
@springminhcm 如果音频文件没有问题，那有可能是某个依赖库的问题，可以升级一下与读取音频相关的依赖库

**Comment by springminhcm** [comment]
@yeyupiaoling 板主你好，后来我上网找了一下，国外有网友说调num_workers=0，结果.....非常奇怪，真的是调完num_workers后，就不会有这个zipfile.BadZipFile: Bad magic number for file header的讯息了.....个人猜测是否在多进程的关系，以前我都以为num_workers跟cpu有相关，但现在cpu都10核、20核起跳，真的蛮奇怪的，设2也不行，竟要设为0才有办法。@@

**Comment by yeyupiaoling** [comment]
设置成0，后面就没有出现过了吗？

**Comment by springminhcm** [comment]
@yeyupiaoling  Yes!!设置成0，后面就没有出现过了~
