### ISSUE TITLE
NaN or Inf found in input tensor

### ISSUE THREAD

**Issue by GoldenLinlin** [yeyupiaoling/Whisper-Finetune#70]
![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/93275028/f44c2b45-8a41-4008-a973-e8aa5477312c)
您好，当我用两个卡训练时出现这种错误：NaN or Inf found in input tensor，但是同样的数据只用一个卡的时候没有，这是因为什么呢？
两个训练代码间唯一的改动只有CUDA_VISIBLE_DEVICES=1,2与CUDA_VISIBLE_DEVICES=1
<img width="530" alt="471d187e3b9db22365fb193f2060913" src="https://github.com/yeyupiaoling/Whisper-Finetune/assets/93275028/e9d93d0c-1e54-4882-b167-e867df789483">

**Comment by GoldenLinlin** [comment]
采用的模型为：whisper-large-v3

**Comment by yeyupiaoling** [comment]
@GoldenLinlin 你看看是不是学习率太大了，或者数据有问题
