### ISSUE TITLE
建議您整理一下 requirements.txt 及 readme.md 

### ISSUE THREAD

**Issue by bardenthenry** [yeyupiaoling/Whisper-Finetune#71]
若按照您教學的版本安裝環境，faster whisper 會無法使用，因為最新版的僅支援 cuda 12，但您的 readme 中的安裝環境還停留在 cuda 11

**Comment by yeyupiaoling** [comment]
只要你安装的pytorch支持cuda 12就可以的，这个跟我的requirements.txt没有关系，主要是看你安装了那个版本的pytorch。我目前也只是使用cuda11,8，一直没有问题
