### ISSUE TITLE
Belle-whisper-large-v3-zh 没法输出标点符号

### ISSUE THREAD

**Issue by jianchaozhuang** [yeyupiaoling/Whisper-Finetune#73]
不管如何调整prompt参数(去掉也不行)，结果还是没有标点符号的， 是哪里姿势不对吗？ 是通过xinference部署的。
<img width="925" alt="image" src="https://github.com/yeyupiaoling/Whisper-Finetune/assets/124876472/a674e0e0-bb7a-4e68-812f-35d007cd53c4">

**Comment by yeyupiaoling** [comment]
我没有用过这个这个模型。建议你用官方的模型
