### ISSUE TITLE
tools/create_wenetspeech_data.py报错

### ISSUE THREAD

**Issue by Larry-Ye** [yeyupiaoling/Whisper-Finetune#75]
![image](https://github.com/yeyupiaoling/Whisper-Finetune/assets/71308801/dfdeabc8-f945-4f1f-b740-64f89203043c)
不知道怎么在wenetspeech数据集上训练，不知道大佬方不方便写个教程。

**Comment by yeyupiaoling** [comment]
@Larry-Ye 在`tools/create_wenetspeech_data.py`有处理脚本
