### ISSUE TITLE
Push to Hub Support

### ISSUE THREAD

**Issue by sanchit-gandhi** [yeyupiaoling/Whisper-Finetune#78]
Hey @yeyupiaoling! Thanks for building such a valuable resource for the Whisper community 🤗 It would be much appreciated to acknowledge the original Whisper fine-tuning [blog post](https://huggingface.co/blog/fine-tune-whisper) in the [references](https://github.com/yeyupiaoling/Whisper-Finetune/blob/master/README_en.md#reference), from which much of the fine-tuning code is inspired.

In addition, it would great to add `push_to_hub` support to upload model checkpoints directly to the [Hugging Face Hub](https://huggingface.co/) during training. The Hub provides:

* Integrated version control: you can be sure that no model checkpoint is lost during training.
* Tensorboard logs: track important metrics over the course of training.
* Model cards: document what a model does and its intended use cases.
* Community: an easy way to share and collaborate with the community!

To date, there are over **10 thousand** fine-tuned Whisper checkpoints on the Hub. Enabling Hub support would grow the Chinese Whisper community further, particularly through the efforts of this repository!

**Comment by yeyupiaoling** [comment]
@sanchit-gandhi Thank you for your contribution.

**Comment by sanchit-gandhi** [comment]
Thank you @yeyupiaoling!
