### ISSUE TITLE
多卡训练卡死

### ISSUE THREAD

**Issue by qaz159qaz159** [yeyupiaoling/Whisper-Finetune#80]
我用多卡训练结果会卡死在eval完之后，想问下有人遇到这情况吗，又怎么解决的呢？

**Comment by yeyupiaoling** [comment]
我多开是正常的，你有没有安装我项目要求的pytorch版本和transformers版本。
另外你是不是在群里提过这个问题。
后面如果我复现这个问题，会在群里通知的。
