### ISSUE TITLE
whisper medium ct2 int8量化之后十多段话集中在一起输出

### ISSUE THREAD

**Issue by joseph16388** [yeyupiaoling/Whisper-Finetune#82]
whisper medium ct2 int8量化之后十多段话集中在一起输出（出现概率大概是百分之一），这是什么原因呢？

**Comment by yeyupiaoling** [comment]
是不是微调过的模型？如果是，微调过的的确有可能丢失时间戳能力。

**Comment by joseph16388** [comment]
> 是不是微调过的模型？如果是，微调过的的确有可能丢失时间戳能力。

只是int8量化了原始whisper的模型哦
