### ISSUE TITLE
缺少噪音文件夹问题，dataset/noise

### ISSUE THREAD

**Issue by yddnrg** [yeyupiaoling/Whisper-Finetune#85]
在数据增强的过程中，看代码是需要一些噪声文件，但是实际上没有噪音文件夹（dataset/noise），在reader.py中该部分会报错，注释掉可以正常运行
但是希望可以通用噪声来增强数据，求教怎么解决
![image](https://github.com/user-attachments/assets/50a7af8c-17bb-40aa-add8-a2835b019699)

**Comment by yeyupiaoling** [comment]
如果没有噪声文件，可以在配置文件里面设置prob为0就可以了。如果有噪声文件，可以把噪声文件放在dataset/noise文件夹就可以了。
