### ISSUE TITLE
能在添加个音色识别的功能吗？就是这句话是那个人说的。

### ISSUE THREAD

**Issue by triumph** [yeyupiaoling/Whisper-Finetune#86]
能在添加个音色识别的功能吗？就是这句话是哪个人说的。
https://github.com/MahmoudAshraf97/whisper-diarization  我看这个开源项目可以，不知道大神能借鉴一下不？
这样就可以做到语音会议记录的的整理了，对应到具体的人了。

1
00:00:03,580 --> 00:00:09,100
Speaker 0: 喂   你 好 你 好   我 想 提 一 下 一 些 法 律 問 題 你

2
00:00:09,200 --> 00:00:09,860
Speaker 1: 說 什 麼 問 題

3
00:00:11,500 --> 00:00:21,440
Speaker 0: 就 是 我 在 網 上 買 東 西 給 人 騙 了 他 叫 我 付 款 給 他 然 後 我 付 款 了 但 是 他 沒 有 給 我 東 西

4
00:00:24,460 --> 00:00:25,380
Speaker 1: 那 你 這 個 金

5
00:00:25,480 --> 00:00:28,700
Speaker 0: 額 大 不 大 呀 幾 百 塊 吧

6
00:00:30,540 --> 00:00:38,200
Speaker 1: 几 百 块 钱 啊 你 这 个 如 果 是 诈 骗 的 话 你 是 你 诈 骗 的 话 但 是 你 的 信 号 太 小 我 恐 怕 也 1 .

7
00:00:38,200 --> 00:00:40,460
Speaker 1: 2 然 后 你 后 面 联 系 还 联 系 得 上 他 吗

**Comment by ILG2021** [comment]
@triumph 
使用whisperx即可
