### ISSUE TITLE
使用4090 lora微调速度还是很慢，不知道是什么原因

### ISSUE THREAD

**Issue by ILG2021** [yeyupiaoling/Whisper-Finetune#87]
最近用4090 lora微调近10小时的数据，发现训练的比较慢。因为显存不够，模型开启了8bit。是因为这个原因吗？A6000 Ada会快点嘛？

**Comment by yeyupiaoling** [comment]
@ILG2021 开量化是训练比较慢的，如果你有足够的显存，可以不开

**Comment by ILG2021** [comment]
好的，到时候对比尝试下。
