### ISSUE TITLE
想问一下大佬，如果想自己加部分数据进数据集里炼，该怎么操作？

### ISSUE THREAD

**Issue by tuzibuqiahuluobo** [yeyupiaoling/Whisper-Finetune#93]
或者说准备自己的数据集

**Comment by yeyupiaoling** [comment]
参考这个文档，生成对应的数据列表就可以了，
https://github.com/yeyupiaoling/Whisper-Finetune?tab=readme-ov-file#%E5%87%86%E5%A4%87%E6%95%B0%E6%8D%AE
