### ISSUE TITLE
Finetuning for multiple languages

### ISSUE THREAD

**Issue by rose-jinyang** [yeyupiaoling/Whisper-Finetune#95]
Hello
How are you?
Thanks for contributing to this project.
Is it possible to fine-tune Whisper model using this project for multiple languages at same time?

**Comment by yeyupiaoling** [comment]
@rose-jinyang Hello, multi-language support, when making the data list, the `language` field specifies the corresponding language,

```
{
  "audio": {
    "path": "dataset/0.wav"
  },
  "sentence": "近几年，不但我用书给女儿压岁，也劝说亲朋不要给女儿压岁钱，而改送压岁书。",
  "language": "Chinese",
  "sentences": [
    {
      "start": 0,
      "end": 1.4,
      "text": "近几年，"
    },
    {
      "start": 1.42,
      "end": 8.4,
      "text": "不但我用书给女儿压岁，也劝说亲朋不要给女儿压岁钱，而改送压岁书。"
    }
  ],
  "duration": 7.37
}
```
